FROM container4armhf/armhf-alpine
RUN apk update && \
    apk upgrade && \
    apk add nginx && \
    adduser -S www-data && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log && \
    chown -R www-data:www-data /var/lib/nginx


ADD public /app/content
ADD dist /app/content
CMD ["nginx", "-g", "daemon off;"]